version: '3.8'

services:
  komga-narrowcasting-app:
    image: zukzuk/narrowcasting  # This names your image as zukzuk/narrowcasting
    build: .
    ports:
      - "3001:3000"
    env_file:
      - .dev.env
