services:
  narrowcasting-app:
    build:
      context: .
      dockerfile: scripts/Dockerfile.dev
      args:
        APP_VERSION_TAG: ${APP_VERSION_TAG}
    image: zukzuk/narrowcasting:${APP_VERSION_TAG}
    ports:
      - "3001:3000"
    env_file:
      - deploy/public.env
      - .secrets/private.env
      - dev.env
    volumes:
      - .:/usr/src/app            # Mounts the current directory into the container
      - /usr/src/app/node_modules # Creates an anonymous volume for node_modules to prevent folder collision
    environment:
      - APP_VERSION_TAG=${APP_VERSION_TAG}