services:
  komga-narrowcasting-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION_TAG: ${VERSION_TAG}
    image: zukzuk/narrowcasting
    ports:
      - "3001:3000"
    env_file:
      - .dev.env
