services:
  narrowcasting-app:
    build:
      context: .
      dockerfile: scripts/Dockerfile.dev
      args:
        APP_VERSION_TAG: ${APP_VERSION_TAG}
    image: zukzuk/narrowcasting:${APP_VERSION_TAG}
    ports:
      - "3001:3000"
    env_file:
      - deploy/public.env
      - .secrets/private.env
      - dev.env
    volumes:
      - ./dist:/usr/src/app/dist                        # Mounts the dist folder
      - ./src:/usr/src/app/src                          # Mounts the src folder
      - ./types:/usr/src/app/types                      # Mounts the types folder
      - ./deploy:/usr/src/app/deploy                    # Mounts the deploy folder
      - ./mounts/playnite:/usr/src/app/mounts/playnite  # Mounts the playnite backup folder
      - ./mounts/comics:/usr/src/app/mounts/comics      # Mounts the comics server folder
    environment:
      - APP_VERSION_TAG=${APP_VERSION_TAG}