# Use a Debian-based Node.js image
FROM node:20-alpine

# Accept args as build arguments
ARG VERSION_TAG
ENV VERSION_TAG=$VERSION_TAG

# Set up the working directory
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./

# Install all dependencies, including dev dependencies
RUN npm install

# Copy application code
COPY . .

# Install nodemon globally for hot reloading
RUN npm install -g nodemon

# Expose the port
EXPOSE 3000

# Use nodemon to start the app
CMD ["nodemon", "-L", "server/index.js"]
