services:
  narrowcasting-app:
    image: zukzuk/narrowcasting
    ports:
      - "3001:3000"
    env_file:
      - public.env
      - private.env
    restart: always
    networks:
      - narrowcasting
    extra_hosts:
      - "comics.daveloper.nl:host-gateway"

networks:
  narrowcasting:
    driver: bridge