services:
  narrowcasting-app:
    image: zukzuk/narrowcasting
    ports:
      - "3001:3001"
    env_file:
      - public.env
      - private.env
    volumes:
      - /volume1/Games/Playnite:/usr/src/app/mounts/playnite
      - /volume1/Comics:/usr/src/app/mounts/comics
    restart: always
    networks:
      - narrowcasting
    extra_hosts:
      - "comics.daveloper.nl:host-gateway"
      - "cinema.daveloper.nl:host-gateway"

networks:
  narrowcasting:
    driver: bridge