# Use a Debian-based Node.js image
FROM node:20-alpine

# Accept args as build arguments
ARG APP_VERSION_TAG
ENV APP_VERSION_TAG=$APP_VERSION_TAG
# npm will install dependencies and devDependencies
ENV NODE_ENV=development

# Set up the working directory
WORKDIR /usr/src/app
COPY *.json ./
COPY *.env ./
RUN npm install

# Expose the port
EXPOSE 3001

# Use a script to continuously compile TypeScript and watch for changes
CMD ["npx", "concurrently", "\"npm run internalscript:npx:tsc\"", "\"npm run internalscript:npx:nodemon\""]