# Use a Debian-based Node.js image
FROM node:20-alpine

# Accept args as build arguments
ARG APP_VERSION_TAG
ENV APP_VERSION_TAG=$APP_VERSION_TAG
# npm will install dependencies and devDependencies
ENV NODE_ENV=development 

# Set up the working directory
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install

# Copy application code
COPY . .

# Build the project (copies the public folder and compiles TypeScript)
RUN npm run build

# Expose the port
EXPOSE 3000

# Use a script to continuously compile TypeScript and watch for changes
CMD ["npx", "concurrently", "\"npx tsc --watch --preserveWatchOutput --watchFile fixedpollinginterval\"", "\"npx nodemon -L\""]